language: node_js
node_js:
- iojs
- '6'
deploy:
  provider: heroku
  api_key:
    secure: btr5xUC9hfkAMx0c6g+BC61ilmowiEL2YRVWMaV98LFO7Gto+NkWRoBLP/Hv9iAYO/Z2Ajh8QXN0Wwivgoa0Afvo5NWLh9SxutK/aqrq57/YL6sYAs6sRbE0X24AqYgdSiuMAMmIm5MP3R5QEXLrGoi1B6xpEi7M3IsfCiXU6VbB0hazSExnnsPkHJYopkCfKl0CK/Uoi36EmwZIIU9jjCYPaTiJZXFRoqF15HdYd0P9quXmCdtjlIHFNsDjeMLrRZPNcYuLXioj/6EVbzWByCNsQrQC0/qQ0mIhDm5uqvXgd8nut85I7bbGVV21lm0wd3ZjuoZvbC+kIm9D2HCFpsebps5EQuPvZvNpTM2xSU578rtTTCEwo7A01Me4+hNmvp2CnP0/1FQlM/uLFK18hZbrPoiulf32gFdza0LKdW2zeWSf9eVOKzMWv9oHNpNFqrlLSRDpX5eTBEc7pn1LfPpfNmeNkCG8w/MIIy0tKsgpQ0OmhCO+KtMss1e3vQ4gyk/Yr0kIF2CMWI+MgKxePWYHcNBnHNXGXXq6QMjgEVJcwhm0FbM0pdsWolu3G3edfTzSUcsOB9/bq8Mekl/jek+hnWNFqRoQu0cjgIKuOK/+MXlYxWVMTEGlIMcPZqVGbJGIaDCiOg/oYyANMZlX7Y9vUIQREcJOo9oEU/1o1X8=
  app: 
    master: descent-saver
